### ISSUE TITLE
Generated open-object index signatures break Pick/Omit source compatibility

### ISSUE THREAD

**Issue by bokelley** [adcontextprotocol/adcp-client#2573]
## Summary

SDK 14 adds string index signatures to generated open-object interfaces. This breaks standard TypeScript utility types such as `Omit`/`Pick`: named properties collapse to `unknown`/`{}` because `keyof` becomes `string | number`.

The same adopter source compiles with `@adcp/sdk@13.0.0` and fails with `14.0.0-beta.1`, despite the migration guide saying established 3.x tools can continue unchanged.

## Minimal reproduction

```ts
import type { CreativeBrief } from '@adcp/sdk'

type BriefWithoutName = Omit<CreativeBrief, 'name'>

declare const brief: BriefWithoutName
brief.messaging?.headline
```

With SDK 13: compiles.

With SDK 14 beta.1:

```text
error TS2339: Property 'headline' does not exist on type '{}'.
```

SDK 13 generated `CreativeBrief` with named properties only. SDK 14 adds `[k: string]: unknown | undefined` to `CreativeBrief` and nested open objects. That makes `Omit<CreativeBrief, 'name'>` effectively an index-signature-only type and loses the named property types.

This pattern also makes structurally equivalent adopter interfaces fail assignment to generated types because the generated target requires a string index signature.

## Expected

Open JSON Schema objects should remain forward-compatible without making generated named interfaces unusable with TypeScript utility types. Possible approaches include a generated helper that preserves known keys, separating the extension bag, or avoiding an index signature on exported named interfaces while keeping runtime schemas permissive.

Please add an SDK 13 source-compat fixture corpus to `check:adopter-types` that compiles representative `Pick`, `Omit`, extension, and structural-assignment patterns against both releases. The current minimal adopter-type guard does not catch this class of regression.

## Environment

- Passing: `@adcp/sdk@13.0.0`
- Failing: `@adcp/sdk@14.0.0-beta.1`
- `strict: true`, `moduleResolution: NodeNext`

**Comment by bokelley** [comment]
## Triage

**Classification:** Bug — type surface regression in SDK 14 beta codegen
**Bucket(s):** library
**Status:** ready-to-implement

**What the experts said:**
- ad-tech-protocol-expert: Bug confirmed; no protocol requirement for index signatures on named TypeScript interfaces — `additionalProperties: true` is a JSON Schema runtime constraint that Zod schemas already handle; the TypeScript type layer should remain index-signature-free; OpenRTB 2.6 typings resolved the same question in 2023 by restricting index sigs to explicit `Ext` extension maps only.
- code-reviewer (direct inspection): `scripts/generate-types.ts` already has the right intent — lines 2105/2130 explicitly force `additionalProperties: false` to "Disable [k: string]: unknown for type safety" — but those guards aren't applied uniformly, so `CreativeBrief` and other open-object schemas slip through in SDK 14 beta.

**My take:** This is a clear regression in the codegen step introduced in SDK 14 beta before stable release. The Zod runtime schemas (`schemas.generated.ts`) already preserve `additionalProperties: true` for wire permissiveness — the TypeScript interface layer doesn't need to duplicate it, and doing so silently collapses `Omit`/`Pick` into `{}`. Fix scope is narrow and mechanical.

**Implementation brief:**

- **`scripts/generate-types.ts`** — Audit every call site that feeds a schema object to `compile()`. Extend the existing `additionalProperties: false` guard (pattern from lines 2105/2130) to cover all named-export compilation paths. The `enforceStrictSchema()` function at line ~660 is the right insertion point — add a guard that strips index-signature-producing `additionalProperties: true` from the top-level and nested named objects before compilation, applying the same logic that already exists for the select branches.
- **`scripts/check-adopter-types.ts`** — Extend `ADOPTER_SOURCE` with: `type _BriefWithoutName = Omit<CreativeBrief, 'name'>` + `declare const b: _BriefWithoutName; b.messaging?.headline;`, a `Pick<CreativeBrief, 'messaging'>` exercise, and a structural-assignment guard (`const _: CreativeBrief = { name: 'x', ...rest }` without requiring index sig). These patterns directly reproduce the reported regression and will catch any future recurrence.
- **Re-run codegen** — `npm run generate-types` (and the v3.1-beta variant) to regenerate `.generated.ts` files after the template fix; do not edit `.generated.ts` files by hand.
- **Changeset** — `npm run changeset` (patch bump: restoring source compat lost in beta).
- **CI gates** — `npm run ci:quick`, `npm run ci:schema-check`, `npm run check:adopter-types`.

Non-breaking rationale: SDK 14 is still in beta; this removes a regression before the stable release, restoring SDK 13 source compatibility as the migration guide promised. The Zod runtime layer is untouched and remains `additionalProperties: true` permissive.

---
Triaged by Claude Code. Session: https://claude.ai/code/session_01G5Va5WyKhGxFehwo6yXm3T

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by bokelley** [comment]
**Follow-up from the code-reviewer pass — implementer note:**

Both existing guards already exist (`enforceStrictSchema()` call + `additionalProperties: false` at every `compile()` site). The index signatures survive because of two specific gaps, not a missing top-level strip:

1. **`enforceStrictSchema`, lines 859–860** — after merging an allOf/`$ref` base, the code re-introduces `additionalProperties` from the resolved base (`if strictSchema.additionalProperties === undefined && resolved.additionalProperties !== undefined`). This undoes the earlier strip. Fix: strip it *after* the merge, not before.

2. **`expandDiscriminatorEnum`, line 510** — copies `schema.additionalProperties` to every discriminator branch before those branches are processed by `enforceStrictSchema`. If the recursive path doesn't re-enter the strip for deeply nested shapes, they survive. Fix: verify the oneOf branch path routes through `enforceStrictSchema`, or strip `additionalProperties: true` from each branch immediately after the copy.

A patch that only adds a pre-`compile()` strip or a top-level `enforceStrictSchema` call will miss one or both of these paths and the regression will reappear on any discriminated allOf schema.

---
Triaged by Claude Code. Session: https://claude.ai/code/session_01G5Va5WyKhGxFehwo6yXm3T

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by bokelley** [comment]
Beta.2 fixes the original `CreativeBrief` + `Omit` reproduction, but nested named shapes still retain source-incompatible index signatures. This minimal public-barrel reproduction fails with `@adcp/sdk@14.0.0-beta.2`:

```ts
import type { LegacyProduct, ProductCardFields } from '@adcp/sdk'

declare const helperCard: ProductCardFields
const generatedProductCard: NonNullable<LegacyProduct['product_card']> =
  helperCard
```

```text
Type 'ProductCardFields' is not assignable to type '{ [k: string]: unknown; ... }'.
  Index signature for type 'string' is missing in type 'ProductCardFields'.
```

This is especially surprising because both sides are exported by the same package. `ProductCardFields` comes from the projection builder surface, while the inline `LegacyProduct.product_card` compilation still includes `[k: string]: unknown`.

The same residual pattern appears throughout a real SDK 13 adopter migration: beta.2 reduces our storefront-adapter check from 423 errors in 81 files to 354 errors in 76 files, but many remaining errors are nested index-signature incompatibilities (`ProductCardDetailedFields`, package results, event-source health/diagnostic issues, and similar generated inline shapes).

Could this issue be reopened or followed by a complete recursive/nested named-shape fix? Please add the public-barrel fixture above to `check-adopter-types`; the original top-level `Omit` fixture alone does not cover the remaining regression.

**Comment by bokelley** [comment]
## Triage

**Classification:** Bug — residual nested inline-shape index signature (same bug class, incomplete beta.2 fix)
**Bucket(s):** library
**Status:** ready-to-implement
**Re-triage trigger:** MEMBER follow-up confirming beta.2 is partial

**What the experts said:**
- javascript-protocol-expert: Confirmed — beta.2 fixed the allOf-merge re-introduction and discriminator-branch copy paths, but jsts' global `additionalProperties: false` compiler option only applies to the root schema document, not to nested inline object schemas; `enforceStrictSchema` deletes explicit `true` but doesn't set explicit `false`, so jsts defaults back to open for nested shapes like `product_card`.

**My take:** One targeted addition to `enforceStrictSchema` + three missing test fixtures closes the remaining regression. Fix is non-breaking (type narrowing only; Zod/runtime layer is untouched).

**Implementation brief:**

- **`scripts/generate-types.ts` — `enforceStrictSchema` ~line 751–753**: After stripping `additionalProperties === true`, also set `strictSchema.additionalProperties = false` when `strictSchema.type === 'object' && strictSchema.properties && strictSchema.additionalProperties === undefined`. The second properties-recursion at line ~930–934 already calls `enforceStrictSchema(value)` on each property schema, so this change propagates automatically to all nested inline objects.
- **`scripts/check-adopter-types.ts`**: Add (1) `const x: NonNullable<LegacyProduct['product_card']> = helperCard` (the exact failing pattern), (2) `type _T = Omit<NonNullable<LegacyProduct['product_card']>, 'title'>` (utility type on inline shape), (3) reverse-assignability guard.
- Re-run codegen after template fix; do not hand-edit generated files.
- `npm run changeset` (patch), then `npm run ci:quick` + `npm run check:adopter-types`.

Please reopen this issue or file a follow-up to track the remaining 354 errors.

---
Triaged by Claude Code. Session: https://claude.ai/code/session_019as5XSSGqUK1kFjBqB7Rt1

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by bokelley** [comment]
Verified the published `@adcp/sdk@14.0.0-beta.3`: the original `CreativeBrief` `Omit`, structural `ProductCardFields`, canonical `Product.product_card`, and nested `LegacyProduct.product_card` reproduction now all compile. The recursive nested index-signature gap reported against beta.2 is fixed.

The overall beta.3 compatibility run still has unrelated generated-type failures; I separated the largest concrete regression into #2611 (`core.generated` emits `SyncCreativesSuccess.creatives` as `{}` items while `tools.generated` emits the correct fields).
